# Generated by Django 4.1.1 on 2022-11-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("it", "0002_alter_meal_id_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="user",
            new_name="id_user",
        ),
    ]
