# Generated by Django 4.1.4 on 2023-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("it", "0003_rename_user_client_id_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
